# Telegram Configuration
telegram:
  api_id: '22544328'
  api_hash: 'c9b5f81a263933e3fecce08cc719fa00'
  phone_number: '+919702270708'
  channels:
    - 'amazonindiaassociates'
    - 'realearnkaro'

# Telegram Bot Configuration for Forwarding
telegram_bot:
  token: '6831241416:AAEamtwesUyXH5NBAGt3gLzMBsabgahGL9o'
  channel: '@dealstodayindia001'
  phone_number: '+919702270708'

# Instagram Configuration
instagram:
  username: 'trendingoffers5'
  password: 'vishu@1992'

# Optional: URL Parameters to Add
url_params:
  tag: 'offerscode08-21'
  affid: 'vishwajit8'
  ref: 'offerscode21'

# Optional: Bitly URL Shortening
bitly:
  access_token: '5ce0605d81302ac039faf49be37ec90c843cd62b'

# Optional: Facebook Posting
facebook:
  access_token: 'EAADjpjJBmTMBO1jab7vDC1v4CDFi6eaPpZCqLHQ1pMeLZCGxSSw5QcXfTNutypY6H5lBZAJ6SJKlPtaRbZBGCa5R3pwqq878BZB8FprCs7jwsZCGPGsU7igCOywe75zoZBIrLgWYHIYK092GPJlWDWV4M2jDmK4ZBexuQS06iPeWjZC2fOYh69PkYQZCpZCFfLSECRc6SYxxiEqTGjdBLoZD'
  page_id: '105896528030351'
